language: python
python: 3.6                     # type annotations introduced in this version
env:
  - LOG_LEVEL=INFO

before_install: make dependencies
install: make install
script:
  - make test
  - make check
