language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
cache:
  - apt
  - directories:
    - emacs-24.3
before_install:
  - sudo make travis-dependencies
install:
  - make tangle
  - pip install .
script:
  - make _check
