language: python
python:
  - "3.2"
  - "3.3"
cache:
  - apt
  - directories:
    - emacs-24.3
before_install:
  - brew install sdl sdl_image sdl_mixer sdl_ttf portmidi hg
  - sudo pip install networkx hg+http://bitbucket.org/pygame/pygame nose
  - make --silent emacs24
  - sudo make --silent installemacs24
  - emacs --version
install:
  - make tangle
  - pip install .
script: make _check
