language: python
python:
  - "3.2"
  - "3.3"
cache:
  - apt
  - directories:
    - emacs-24.3
before_install:
  - sudo apt-get install python-pygame
  - make --silent emacs24
  - sudo make --silent installemacs24
  - emacs --version
install:
  - make tangle
  - pip install .
script: make _check
