language: python
python:
  - "3.2"
  - "3.3"
before_install:
  # Need at least emacs > 24.0
  - make emacs24 > /dev/null
  - alias emacs='emacs-24.3/src/emacs --no-window-system'
  - emacs --version
  # Aptitude will install all dependencies of PyGame.
  - sudo apt-get install python-pygame
install:
  - make tangle
  - pip install .
script: make check
