language: python
python:
  - "3.2"
  - "3.3"
before_install:
  - sudo pip install nose
  - sudo apt-get install python-pygame
  - make --silent emacs24
  - sudo make --silent installemacs24
  - emacs --version
install:
  - make tangle
  - sudo pip install .
script: sudo make _check
