language: python
python:
  - "3.2"
  - "3.3"
before_install:
  - sudo apt-get install hg python-pygame
  - sudo pip install nose hg+http://bitbucket.org/pygame/pygame
  - make --silent emacs24
  - sudo make --silent installemacs24
  - emacs --version
install:
  - make tangle
  - pip install .
script: make _check
